# Generated by Django 4.0 on 2021-12-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_project_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_photo',
        ),
    ]
